export const DUMMYPRODUCTS: any[] = [
    {
        id: 1,
        comp_Material: 1,
        comp_MaterialName: "Int 1",
        rawMaterial1: 1,
        rawMaterial1Name: "Raw Material 1",
        rawMaterial2: 2,
        rawMaterial2Name: "Raw Material 2",
        name: "FG 1",
        quantity: 50,
    },
    {
        id: 2,
        comp_Material: 1,
        comp_MaterialName: "Int 1",
        rawMaterial1: 1,
        rawMaterial1Name: "Raw Material 1",
        rawMaterial2: 2,
        rawMaterial2Name: "Raw Material 2",
        name: "FG 2",
        quantity: 50,
    },
    {
        id: 3,
        comp_Material: 1,
        comp_MaterialName: "Int 1",
        rawMaterial1: 1,
        rawMaterial1Name: "Raw Material 1",
        rawMaterial2: 2,
        rawMaterial2Name: "Raw Material 2",
        name: "FG 3",
        quantity: 50,
    }
]